### ISSUE TITLE
The forceOverride parameter in DavResource.move() does the opposite

### ISSUE THREAD

**Issue by zhanghai** [bitfireAT/dav4jvm#39]
Looking at https://github.com/bitfireAT/dav4jvm/blob/b30913f2210811c9e69978d7adf31e1201b10831/src/main/kotlin/at/bitfire/dav4jvm/DavResource.kt#L191

The code only sets `Overwrite: F` when `forceOverride` is `true`, however `A value of "F" states that the server should not perform the COPY Method or MOVE Method if the state of the destination resource is not null` ([source](https://learn.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2003/aa142944(v=exchg.65))), which seems to be the opposite.

**Comment by zhanghai** [comment]
Thanks for the speedy fix! Do you have a plan to make a new release in the near future?

**Comment by rfc2822** [comment]
For DAVx5? If you only need it in dav4jvm, you can use it with the commit ID, [like DAVx5 does](https://github.com/bitfireAT/davx5-ose/blob/df2b7d2bd09feba7ce7f0d75c43b0a901e68d002/gradle/libs.versions.toml#L30).
